#!/bin/sh
# Usage: ./html-assemble.sh
# Assemble HTML pages when parts in `en.src` change, and place them under `en`.

set -e

cd en

for html_src in $(find ../en.src -regex '.*/[^_][^/]+\.html'); do
    page="$(basename "${html_src%%.html}")"
    html="$page.html"
    # TODO: Get from content source, but it must be in some translatable tag or attribute.
    # FIXME: When first adding a page, a placeholder page needs to be dropped in `en`
    # so that its title can be extracted here (it can just contain `<title>TITLE</title>`).
    title="$(sed -nE 's#.*<title>(.+)</title>.*#\1#p' "$html" | head -1)"

    tmp="$(mktemp)"
    echo '<!-- WARNING: Please do not edit this file directly, edit files in "en.src" instead. -->' >> "$tmp"
    sed -e "s#@PAGE@#$page#g" -e "s#@TITLE@#$title#g" ../en.src/_head.html >> "$tmp"
    cat "$html_src" >> "$tmp"
    sed -e "s#@PAGE@#$page#g" -e "s#@TITLE@#$title#g" ../en.src/_tail.html >> "$tmp"
    mv "$tmp" "$html"
done
