#!/bin/sh
# Usage: ./html-assemble.sh
# Assemble HTML pages when parts in `en.src` change, and place them under `en`.

set -e

cd en

for pot in *.pot; do
    page="${pot%%.pot}"
    html="$page.html"
    # TODO: Get from content source, but it must be in some translatable tag or attribute.
    title="$(sed -nE 's#.*<title>(.+)</title>.*#\1#p' "$html" | head -1)"

    tmp="$(mktemp)"
    echo '<!-- WARNING: Please do not edit this file directly, edit files in "en.src" instead. -->' >> "$tmp"
    sed -e "s#@PAGE@#$page#g" -e "s#@TITLE@#$title#g" ../en.src/_head.html >> "$tmp"
    cat "../en.src/$html" >> "$tmp"
    sed -e "s#@PAGE@#$page#g" -e "s#@TITLE@#$title#g" ../en.src/_tail.html >> "$tmp"
    mv "$tmp" "$html"
done
